### PR TITLE
point landing page image to /static instead of external url

### PR DESCRIPTION
**Pull request by paulgeronca**

### CODE REVIEW

**Comment by paulgeronca** [comment]
> Good: this is now pointing to the static image I had uploaded along with my other landing page fixes (couldn't get this working locally initially but seems to be now).

Yeah, I saw that! Best guess is that it was pointing to the file at ../../public/static/ , which wouldn't actually resolve to where they end up in staging or production.

**Comment by paulgeronca** [comment]
[https://github.com/hackla-engage/engage-client/issues/163](url)

**Comment by eselkin** [comment]
Any reason why this wasn't merged?

**Comment by joshbeme** [comment]
@eselkin in teddy's pr he is taking out the picture making this pr redundant.

**Comment by paulgeronca** [comment]
Ok it reads much better without the bg

**Pull request closed without merging**
