### PR TITLE
Added the ability to share the proposal URL 

### PR DESCRIPTION
**Pull request by IsmaelVazquez**
Solution to Issue #78 

I installed a package called react-share.

A few buttons were added to the bottom of the proposal page(AgendaItem.jsx in the "recommended action" card).
screen shot 2018-08-04 at 5 51 58 pm

I also created a new file called ShareButtons.scss for some minor styling of the aforementioned buttons.

### CODE REVIEW

**Comment by JerryLeeCS** [comment]
Looks good!

**Comment by eselkin** [comment]
convertToNormal time should have been replaced by the packages date-fns that does a more robust job at formatting from timestamps.

**Comment by owenjoseph** [comment]
@IsmaelVazquez will you have a chance to look at this in the next few weeks? Otherwise I can tag it "Help Wanted"

cc @TeddyCr @eselkin @JerryLeeCS @miahuynh

**Comment by TeddyCr** [comment]
I tagged it as `Help needed` and updated the issue #78

**Comment by seport** [comment]
regarding the facebook issue, it seems like it should work on production, maybe https://github.com/nygardk/react-share/issues/144

I'll take a look at the other issues :)

**Comment by owenjoseph** [comment]
@TeddyCr @eselkin I'm closing this in light of #139; are there any follow-up actions we should take?

**Pull request closed without merging**
